export const nicheOptions = [
  { label: "Lifestyle", value: "lifestyle" },
  { label: "Fashion", value: "fashion" },
  { label: "Beauty", value: "beauty" },
  { label: "Technology", value: "technology" },
  { label: "Gaming", value: "gaming" },
  { label: "Travel", value: "travel" },
  { label: "Food", value: "food" },
  { label: "Health & Wellness", value: "health_wellness" },
  { label: "Personal Finance", value: "personal_finance" },
  { label: "Home Decor", value: "home_decor" },
  { label: "Gardening", value: "gardening" },
  { label: "Sports", value: "sports" },
  { label: "Entertainment", value: "entertainment" },
  { label: "Education", value: "education" },
  { label: "Business & Entrepreneurship", value: "business_entrepreneurship" },
  { label: "Sustainability", value: "sustainability" },
  { label: "DIY & Crafts", value: "diy_crafts" },
  { label: "Parenting", value: "parenting" },
  { label: "Pets", value: "pets" },
  { label: "Photography", value: "photography" },
  { label: "Art & Design", value: "art_design" },
  { label: "Music", value: "music" },
  { label: "Film & Television", value: "film_television" },
];
